# Generated by Django 5.2.6 on 2025-10-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
