# Generated by Django 5.2.6 on 2025-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
