# Generated by Django 5.2.6 on 2025-10-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_price_product_off_price_product_availibility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availibility',
            new_name='availability',
        ),
    ]
