# Generated by Django 5.2.6 on 2025-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogreview',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
