# Generated by Django 5.2.6 on 2025-11-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='state',
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='address_line2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
