# Generated by Django 5.2.6 on 2025-12-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_billingdetails_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='user',
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
